### ISSUE TITLE
Make the code more popular

### ISSUE THREAD

**Issue by syheliel** [arvid220u/path-tsp-1.5-approximation#1]
It seems that this code is the first one for [paper](https://epubs.siam.org/doi/abs/10.1137/1.9781611975482.93), would you like to put your repository on [Papers With code](https://cs.paperswithcode.com/)?

**Comment by arvid220u** [comment]
Good idea! I submitted it here: https://ml.paperswithcode.com/paper/a-1-5-approximation-for-path-tsp-1. (For some reason it ended up in the ML portal — if you know how to fix that, please do.) To be clear, though, I'm not sure of how much value this implementation is — it is very slow and not very well-organized or well-documented. But it may be helpful for inspiration :)
